package com.woutwerkman.net

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.channels.ReceiveChannel
import kotlinx.coroutines.channels.SendChannel
import kotlinx.serialization.Serializable

/**
 * Represents a discovered peer on the network.
 */
@Serializable
data class PeerInfo(
    val id: String,
    val name: String,
    val address: String,
    val port: Int
)

/**
 * Messages that can be sent/received over the peer network.
 */
@Serializable
sealed class PeerMessage {
    /**
     * Events generated by the peer network itself (not from other peers).
     */
    @Serializable
    sealed class Event : PeerMessage() {
        /**
         * A peer has joined the network and bidirectional connectivity is verified.
         * This means both we can see them AND they can see us.
         *
         * The internal handshake is handled automatically - consumers only see
         * peers that are fully connected.
         */
        @Serializable
        data class Joined(val peer: PeerInfo) : Event()

        /**
         * A previously connected peer has left the network.
         */
        @Serializable
        data class Left(val peerId: String) : Event()
    }

    /**
     * A message sent by another peer (application-level data).
     */
    @Serializable
    data class Received(
        val fromPeerId: String,
        val payload: ByteArray
    ) : PeerMessage() {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other == null || this::class != other::class) return false
            other as Received
            return fromPeerId == other.fromPeerId && payload.contentEquals(other.payload)
        }

        override fun hashCode(): Int {
            var result = fromPeerId.hashCode()
            result = 31 * result + payload.contentHashCode()
            return result
        }
    }
}

/**
 * Command to send to the peer network.
 */
@Serializable
sealed class PeerCommand {
    /**
     * Send data to a specific peer.
     */
    @Serializable
    data class SendTo(
        val peerId: String,
        val payload: ByteArray
    ) : PeerCommand() {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other == null || this::class != other::class) return false
            other as SendTo
            return peerId == other.peerId && payload.contentEquals(other.payload)
        }

        override fun hashCode(): Int {
            var result = peerId.hashCode()
            result = 31 * result + payload.contentHashCode()
            return result
        }
    }

    /**
     * Broadcast data to all discovered peers.
     */
    @Serializable
    data class Broadcast(
        val payload: ByteArray
    ) : PeerCommand() {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other == null || this::class != other::class) return false
            other as Broadcast
            return payload.contentEquals(other.payload)
        }

        override fun hashCode(): Int = payload.contentHashCode()
    }
}

/**
 * A connection to the peer network, providing channels for sending and receiving messages.
 */
class PeerNetConnection(
    val incoming: ReceiveChannel<PeerMessage>,
    val outgoing: SendChannel<PeerCommand>
)

/**
 * Configuration for the peer network connection.
 */
data class PeerNetConfig(
    val serviceName: String = "chippy",
    val displayName: String = "Peer",
    val discoveryTimeoutMs: Long = 30_000
)

/**
 * Establishes a connection to the peer network for discovering and communicating with other peers on the LAN.
 *
 * The connection handles all the complexity of peer discovery internally:
 * - mDNS/Bonjour service advertisement and discovery
 * - Bidirectional handshake verification (ensuring both peers can see each other)
 * - Keep-alive and timeout management
 *
 * Consumers receive simple events:
 * - [PeerMessage.Event.Joined]: A peer is fully connected (bidirectional connectivity verified)
 * - [PeerMessage.Event.Left]: A peer has disconnected
 * - [PeerMessage.Received]: Application data from a peer
 *
 * Internal protocol messages used for handshaking are hidden from consumers.
 */
suspend fun <T> withPeerNetConnection(
    config: PeerNetConfig = PeerNetConfig(),
    block: suspend CoroutineScope.(PeerNetConnection) -> T
): T = withPeerNetConnectionImpl(config, block)

/**
 * Platform-specific implementation of [withPeerNetConnection].
 */
internal expect suspend fun <T> withPeerNetConnectionImpl(
    config: PeerNetConfig,
    block: suspend CoroutineScope.(PeerNetConnection) -> T
): T
